# Site settings
title: Zorex Salvo
description: 'Junior Developer'
url: 'http://zorexsalvo.github.io'
baseurl: '/'

author:
  name: 'Zorex Salvo'
  email: zorexsalvo@gmail.com
  twitter_username: zorexsalvo
  facebook_username: zorexsalvo
  github_username:  zorexsalvo
  linkedin_username: zorex-salvo-67b486119

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
